### ISSUE TITLE
filtering for indentation of the first paragraph

### ISSUE THREAD

**Issue by pengyu** [tomduck/pandoc-eqnos#1]
I like the idea of using filtering for equation numbering.

Another feature I have been looking at is paragraph indentation. The solutions that I find are not general and adhoc.

https://groups.google.com/forum/#!topic/pandoc-discuss/gdaPWXdRc3U

I think this filtering idea can be applied to this indentation problem. Can you create a filter? Thanks.

**Comment by tomduck** [comment]
Thanks, @pengyu.  It looks like there is a working filter provided in that thread.  See the post by Chris Forster.  Perhaps you could file an issue on [his github repository](https://gist.github.com/c-forster/e312205cefa7d87ebad3) to see if the filter can be improved to better meet your needs?
