### ISSUE TITLE
pandoc-eqnos not found in path

### ISSUE THREAD

**Issue by raffaelevacca** [tomduck/pandoc-eqnos#13]
I'm on Mac OS 10.9.5 
When trying to use pandoc-eqnos I get this:

```
pandoc: Error running filter pandoc-eqnos
pandoc-eqnos not found in path
```

But pandoc-eqnos has been successfully installed and is in `/usr/local/bin`, and `/usr/local/bin` is in my `$PATH`.

Thoughts?

**Comment by tomduck** [comment]
Thanks for the feedback @raffaelevacca, and sorry for the delay.    I too am working on a Mac, so we should be able to sort this out.

Did you install using `pip` or some other way?

Can you please provide me with a minimum (non) working example with your command-line call so that I can try to reproduce the problem?

**Comment by raffaelevacca** [comment]
Yes, I installed using `pip`.
My command-line call is
`pandoc inputfile.md -o outputfile.pdf --filter pandoc-eqnos`
Thanks.

**Comment by tomduck** [comment]
Hmmm.  On my Mac `pandoc-eqnos` gets installed to `/Library/Frameworks/Python.framework/Versions/3.4/bin/pandoc-eqnos`.  Are you using macports or some such thing for your python install?

Please execute `which pandoc-eqnos` at the bash command prompt and let me know the output.  This will tell us whether or not bash can find it.

**Comment by tomduck** [comment]
Hi @raffaelevacca.  I just pushed out a new version of pandoc-eqnos for the new pandoc 1.18.  Can you give it a try to see if this Issue is resolved?  If it is no longer relevant, then please go ahead and close it.

**Comment by raffaelevacca** [comment]
Will do, thank you.

**Comment by tomduck** [comment]
Thanks, @raffaelevacca.  I hope that you were able to get it working.  Cheers, Tom.
