### ISSUE TITLE
restarting the label count

### ISSUE THREAD

**Issue by DevinBayly** [tomduck/pandoc-eqnos#15]
Hi there,

This is probably a pretty simple answer, but how should I go about resetting the count for my numbered equations?

If I finish a section I would like to be able to go back to referring to them as 1 or 2. I know that is potentially going to throw off the referencing though, so is there a workaround?

**Comment by tomduck** [comment]
Hi @DevinBayly.  Thanks for your feedback.  I agree that this would be good to have.  It should be pretty simple to accomplish with latex/pdf, but would require more thought for the other output formats.  So, what output format do you need?

**Comment by tomduck** [comment]
If your document is broken into sections (or chapters), then using the `--number-sections` flag with pandoc gives equation numbers in X.Y format for latex/pdf output.  X is the section number and Y is the equation number in that section.

**Comment by tomduck** [comment]
I just pushed out a new version that enables equation numbering by section.  To activate it, read the section on "Equation Numbers by Section" in the documentation.

I think that this does what you want.  Please let me know.

Cheers,
Tom
