### ISSUE TITLE
Problems and solution for the installation in Kubuntu 14.04

### ISSUE THREAD

**Issue by ouboub** [tomduck/pandoc-eqnos#17]
I had difficulties in installing pandoc-eqnos in Kubuntu 14.04, but I solved it and want to share my
experience with others you have to upgrade the python six module.
so
sudo -H pip install --upgrade six
sudo easy_install -U setuptools
sudo -H pip install pandoc-eqnos
worked and i am enjoying the great extension, thanks!

Uwe Brauer

**Comment by tomduck** [comment]
Hi Uwe.  Thanks for the feedback and sorry for the long delay.  I'm glad that you are finding the extension useful.

I will add a note reflecting your experience to the README.
