### ISSUE TITLE
Converting TeX source to html

### ISSUE THREAD

**Issue by wochristian** [tomduck/pandoc-eqnos#19]
Does pandoc-eqnos work when converting a TeX file to another format, such as html or epub?  In other words, does pandoc-eqnos only work when converting markdown source?
 
I use standard TeX syntax \ref{eq:gaussian} and \label{eq:gaussian} in my TeX source file and it compiles without error using TexStudio on iOS.  However, the reference and label are not converted when use pandoc with the pandoc-eqnos filter.

**Comment by tomduck** [comment]
Hi @wochristian.  Thanks for your feedback and sorry for the long delay.  I'm afraid that pandoc-eqnos and friends are only for providing cross-referencing capabilities to markdown input documents.
