### ISSUE TITLE
Cannot recreate demo tex output

### ISSUE THREAD

**Issue by valencik** [tomduck/pandoc-eqnos#2]
I cannot create the desired output with the input [demo.md](https://github.com/tomduck/pandoc-eqnos/blob/master/demos/demo.md)

``` bash
pip install --upgrade git+https://github.com/tomduck/pandoc-eqnos.git
wget https://raw.githubusercontent.com/tomduck/pandoc-eqnos/master/demos/demo.md
pandoc --filter pandoc-eqnos demo.md -o demo.tex
```

This produces:

```
What is this? {[} y = mx + b {]} \{\#eq:line\} Equation @eq:line
describes a straight line.

More generally, the equation for a polynomial is {[}
\textbackslash{}begin\{aligned\} y \&= a\_0 + a\_1 x + a\_2 x\^{}2 +
a\_3 x\^{}3 + \dots \textbackslash{} \&= \sum\_i a\_i x\^{}i
\textbackslash{}end\{aligned\} {]} \{\#eq:polynomial\}

Equations \{@eq:line\}--\{@eq:polynomial\} are known to all math
students.

Equations like {[} y = A e\^{}\{-\gamma t\}\cos(2\pi f t) {]} can be
left unnumbered if we do not need to refer to them. It is also possible
to number equations generically without planning to refer to them; e.g.:
{[} \pi = 3.141592653589793238462643\dots {]} \{\#eq:\} and {[} e =
2.718281828459045235360287\dots {]} \{\#eq:\}
```

Which is different than [demo.tex](https://github.com/tomduck/pandoc-eqnos/blob/master/demos/out/demo.tex) and fails to build:

```
! Missing $ inserted.
<inserted text>
                $
l.70 a\_3 x\^{}3 + \dots \textbackslash{} \&= \sum

pandoc: Error producing PDF from TeX source
```

**Comment by valencik** [comment]
If you modify [demo.md](https://github.com/tomduck/pandoc-eqnos/blob/master/demos/demo.md) as follows you get the desired TeX output:

```
What is this?
$$ y = mx + b $$ {#eq:line}
Equation @eq:line describes a straight line.

More generally, the equation for a  polynomial is
$$ \begin{aligned}
     y &= a_0 + a_1 x + a_2 x^2 + a_3 x^3 + \dots \\
     &= \sum_i a_i x^i
   \end{aligned}
$$ {#eq:polynomial}

Equations {@eq:line}--{@eq:polynomial} are known to all math students.

Equations like
$$ y = A e^{-\gamma t}\cos(2\pi f t) $$
can be left unnumbered if we do not need to refer to them.  It is also possible to number equations generically without planning to refer to them; e.g.:
$$ \pi = 3.141592653589793238462643\dots $$ {#eq:}
and
$$ e =   2.718281828459045235360287\dots $$ {#eq:}
```

Namely, changing `\[` and `\]` both to `$$`.
Is this satisfactory? I don't actually know if `\[` and `\]` are desired/supported in pandoc.

**Comment by tomduck** [comment]
You can process the original file using the following pandoc option:

```
--from=markdown+tex_math_single_backslash
```

I use `\[` and `\]` for display math, a practice I learned from LaTeX.  But perhaps I should move to using `$$` for the demo for the sake of clarity.

**Comment by valencik** [comment]
Ahhh of course. Thank you.
Well with that in mind, if anything, I would suggest multiple demos showing off both.

Pandoc enables so many possibilities, it is sometimes nice to see concrete examples.

**Comment by tomduck** [comment]
I decided to go with your earlier suggestion, which makes things simpler.  Thanks for pointing it out.

... and equations now have links, as per your request on [pandoc-fignos Issue #5](https://github.com/tomduck/pandoc-fignos/issues/5).

Pandoc-eqnos 0.4 has been pushed to pypi.  Please let me know if you have any difficulties with it.  Enjoy!
