### ISSUE TITLE
Language option

### ISSUE THREAD

**Issue by LibrEars** [tomduck/pandoc-eqnos#21]
Is there a way to write "Equation" in other languages?

~~~
-M lang=de
~~~
as reader option or  writing

~~~
lang: de
~~~

 in the YAML metadata block does not change anything in my setup.

**Comment by jrennstich** [comment]
You could easily do this in the YAML header:

eqnos-plus-name: Eq.
and then use "Gleichung" (or any other term you would like):
eqnos-star-name: Gleichung
eqnos-plus-name: Gl.

**Comment by tomduck** [comment]
Thanks for your feedback, @LibrEars. The answer by @jrennstich is exactly right.  This is the mechanism I had in mind for customizing the reference names.  It is also highly compatible with LaTeX's way of doing things.

Thanks, @jrennstich, for answering this query.

**Comment by LibrEars** [comment]
Works like a charm!

The same for:
fignos-plus-name: Abb.
fignos-star-name: Abbildung

Great! Thanks

**Comment by jrennstich** [comment]
So mache ich das da auch :-) @LibrEars
