### ISSUE TITLE
Support for multiline equations

### ISSUE THREAD

**Issue by pylang** [tomduck/pandoc-eqnos#24]
Is there support using the non-inline style, latex equations, `\begin{equation}...\end{equation}`?  I would like to number equation arrays in the future, `{eqnarray}`.  Example [here](http://www.maths.tcd.ie/~dwilkins/LaTeXPrimer/Multiline.html)

**Comment by tomduck** [comment]
Hi @pylang. Yes, pandoc-eqnos wraps all of its latex equations in `\begin{equation}...\end{equation}`.

**Comment by tomduck** [comment]
Hi @pylang.  I'm assuming that this Issue is no longer a concern.  Please feel welcome to reopen it if there is more to discuss.
