### ISSUE TITLE
Pandoc katex and overwriting

### ISSUE THREAD

**Issue by HaoZeke** [tomduck/pandoc-eqnos#26]
Hi,
For longer equations I seem to be running into an overwriting issue when compiling to html with the --katex flag...
![screenshot-localhost-3002-2017-11-25-21-15-57-754](https://user-images.githubusercontent.com/4336207/33232098-00f86024-d226-11e7-9a50-c7b24a9040bc.png)

The package does not seem to provide any css class and renders the numbers as span elements with inline styles...

Namely:

```html
<span style="position: absolute; right: 0em; top: 50%; line-height:0; text-align: right">(7)</span>
```

**Comment by HaoZeke** [comment]
Actually this can be fixed with CSS, however the span added by pandoc-eqnos has no class attached to it making it hard to target.

**Comment by tomduck** [comment]
Thanks for this report.  I think the solution to this is to move the anchor name into the outer span tag as an id.  e.g., something like this:

~~~
<p><span id="eq:1" style="display: inline-block; position: relative; width: 100%">
    <math display="block" xmlns="http://www.w3.org/1998/Math/MathML">...</math>
    <span style="position: absolute; right: 0em; top: 50%; line-height:0; text-align: right">(1)</span>
</span></p>
~~~

I replaced the mathml with `...` for brevity.

Does this work for you?  It is currently implemented in the `nextrelease` branch.

**Comment by HaoZeke** [comment]
Sorry I'm running late, got exams, I'll test and report back by the end of this week...

**Comment by tomduck** [comment]
I just pushed out a new release candidate for `pandoc-eqnos`, which you can install with `pip` using the `--pre` flag.

**Comment by HaoZeke** [comment]
Unfortunately this isn't working yet... 
![bugpandoc](https://user-images.githubusercontent.com/4336207/34076674-3dd28dea-e314-11e7-88fb-1bc45f89c95c.png)

**Comment by tomduck** [comment]
Thanks, @HaoZeke.  I tried but haven't been able to reproduce the problem you showed.  Here is my markdown in `demo.md`:

~~~
$$ \tau = -\mu(\nabla\mathbf{v}+(\nabla\mathbf{v})^\intercal)
          +\left(\frac{2}{3}\mu - \kappa\right)
          (\nabla\cdot\vec v) \delta $${#eq:fulltau}
~~~

This is the command I used to process it:

    pandoc demo.md --standalone --filter pandoc-eqnos --katex --css demo.css -o demo.html

This is a screen capture of the output:

<img width="500" alt="tmp" src="https://user-images.githubusercontent.com/315246/34076956-03c9fcde-e2cc-11e7-835d-f3fe641d9920.png">

I used the following `demo.css` to color the equation number red:

~~~
span#eq\:fulltau > span:last-child { color:red; }
~~~

I get the same results with both Firefox and Safari.

Any thoughts?

**Comment by tomduck** [comment]
More testing: The results using Chrome are the same as above.

**Comment by tomduck** [comment]
Hi @HaoZeke.  I'm assuming that this is no longer a problem.  In any case, I can't reproduce it.  Please feel welcome to reopen this Issue if you are still having difficulty with it.
