### ISSUE TITLE
Discussion: Will you merge fignos, eqnos and tablenos?

### ISSUE THREAD

**Issue by shixuguo** [tomduck/pandoc-eqnos#28]

**Comment by tomduck** [comment]
Thanks for the question, @shixuguo.  I have thought before about combining the filters into one package, but am leaning toward no.

The `pandoc-xnos` package contains the common code for all of the filters.  So, any upgrades to the core already benefits all three filters.

I could potentially move the filters into `pandoc-xnos`.  However, it seems to me that it would be simpler from a user's standpoint to keep them separate.  Many authors won't need all three filters -- notice, for example, the vastly different number of github stars between the three projects. The combined documentation for all three would definitely be more complex.

If there are arguments for combining them, please let me know.

**Comment by tomduck** [comment]
I'm closing this old Issue.  If there is more interest to discuss, then please feel welcome to re-open it.
