### ISSUE TITLE
Rawgit is shutting down

### ISSUE THREAD

**Issue by averms** [tomduck/pandoc-eqnos#32]
The owner of [rawgit](https://rawgit.com/) is shutting it down. There are 3 rawgit links in your README.
You can try moving to <https://raw.githack.com/> or <https://gitcdn.xyz/>.

**Comment by tomduck** [comment]
Thank you for the heads up.  I have migrated pandoc-eqnos and will do the same for pandoc-fignos and pandoc-tablenos.

Cheers,
Tom
