### ISSUE TITLE
`eqnos-eqref: True` option not working

### ISSUE THREAD

**Issue by tfoerst3r** [tomduck/pandoc-eqnos#35]
I tried to get the equation labeling with brakets running, for example "eq. (1)". But it seems not to work.

I am currently using:

- pandoc 2.6 (same issue with pandoc 2.2.1)
- pandoc-eqnos-1.3.0 
- pandoc-xnos-1.1.1 
- pandocfilters-1.4.2 
- psutil-5.4.8

Example file: __eqnos_test.md__
```
---
title: Test
eqnos-eqref: True
---

# Test

The equation for a straight line is

$$ y = mx + b $$ {#eq:line}

Testline: +@eq:line and @eq:line and \*@eq:line and {@eq:line}.
```

Interpreting it with:

`pandoc --filter pandoc-eqnos --mathjax=/opt/MathJax/MathJax.js?config=TeX-AMS-MML_HTMLorMML --standalone --to=html5 eqnos_test.md`

will result in:

```{.html .numberLines startFrom="001"}
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="" xml:lang="">
<head>
  <meta charset="utf-8" />
  <meta name="generator" content="pandoc" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes" />
  <title>Test</title>
  <style>
      code{white-space: pre-wrap;}
      span.smallcaps{font-variant: small-caps;}
      span.underline{text-decoration: underline;}
      div.column{display: inline-block; vertical-align: top; width: 50%;}
  </style>
  <script src="/opt/MathJax/MathJax.js?config=TeX-AMS-MML_HTMLorMML" type="text/javascript"></script>
  <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv-printshiv.min.js"></script>
  <![endif]-->
</head>
<body>
<header id="title-block-header">
<h1 class="title">Test</h1>
</header>
<h1 id="test">Test</h1>
<p>The equation for a straight line is</p>
<p><span id="eq:line" style="display: inline-block; position: relative; width: 100%"><span class="math display">\[ y = mx + b \]</span><span style="position: absolute; right: 0em; top: 50%; line-height:0; text-align: right">(1)</span></span> </p>
<p>Testline: eq. <a href="#eq:line">1</a> and <a href="#eq:line">1</a> and Equation <a href="#eq:line">1</a> and <a href="#eq:line">1</a>.</p>
</body>
</html>
```

or 

![eqnos](https://user-images.githubusercontent.com/32761865/51320109-21098c80-1a5f-11e9-86b4-f751969fa519.png)

Help would be appreciated. Thx

**Comment by nikcleju** [comment]
I'm also interested in this. The option was added at some point, but it is not read anymore from the file, following some updates. I made a PR for this, and in the mean time I fixed it locally on my machine

**Comment by tomduck** [comment]
Thanks for this feedback and for the PR.  I have fixed it and pushed out a new release.  Please re-open this Issue if you have any further trouble with it.

Cheers,
Tom
