### ISSUE TITLE
Feature Request: Supporting for labelling each equation in a math environment

### ISSUE THREAD

**Issue by ossphil** [tomduck/pandoc-eqnos#38]
It seems that `pandoc-eqnos` supporting labelling each equation in a math environment, which can be implemented in AMS environments, as
```
\begin{align}
  \alpha + \beta = \gamma \label{eq:1}\\
  \frac{a}{b}=c = 0 \label{eq:2}\\
\end{align} 
```
Will `pandoc-eqnos` support this feature in the future?

**Comment by tomduck** [comment]
Thanks for this comment, and sorry for the delay.

I'm not really sure how the [syntax spec](https://github.com/jgm/pandoc/issues/813#issuecomment-70423503) could be adjusted to support such a thing.  We would also need to find a way to support this feature in the other target formats (html, epub).

Any thoughts?

**Comment by tomduck** [comment]
I assume that this issue is no longer of interest, and so am going to close it.  Please re-open if this is not the case.  Note that we would need to have a discussion about the syntax spec (see above) to proceed.  Thanks, Tom.
