### ISSUE TITLE
Error running pandoc --filter pandoc-eqnos

### ISSUE THREAD

**Issue by anntzer** [tomduck/pandoc-eqnos#4]
```
pandoc: Error running filter pandoc-eqnos
fd:4: hClose: resource vanished (Broken pipe)
```

pandoc 1.15.2, python 3.5, Arch Linux.

**Comment by tomduck** [comment]
Hi there.  Sorry for the long delay.

I'm going to need some more information to resolve this issue.  Can you please let me know how you installed pandoc-eqnos?  i.e., was it from source or by using pypi?  Is there a short test markdown file that you can provide me so that I can try to reproduce the error?  Thanks.

**Comment by anntzer** [comment]
I have switched to pandoc 1.15.2.1 (built myself from the sources).  Now, after pip-installing a git checkout of today's HEAD (and pandocfilters and pandoc-attributes from PyPI), cd'ing to the demo folder and removing the "out" folder, I get a different error:

```
$ make
pandoc demo.md --filter pandoc-eqnos -o out/demo.pdf
pandoc: Error in $: not enough input
Makefile:6: recipe for target 'out/demo.pdf' failed
make: *** [out/demo.pdf] Error 1
```

Note that `pandoc demo.md -o out/demo.pdf` works fine (except for the lack of filtering, of course).

**Comment by tomduck** [comment]
I just posted a new pandoc-eqnos 0.5.  If you are getting the same error with this version, then there are a few things we can do to isolate the problem.  In the demo directory, try these commands:

```
pandoc demo.md -t json
pandoc demo.md -t json | python ../pandoc_eqnos.py
pandoc demo.md -t json | python ../pandoc_eqnos.py | pandoc -f json -o demo.pdf
```

The first two should produce a bunch of gobbledygook (json output) but no error messages.  The last one should produce demo.pdf in your current directory.

**Comment by anntzer** [comment]
OK, I figured it out.  Even `pandoc demo.md -t json | python ../pandoc_eqnos.py | pandoc -f json -o demo.pdf` worked for me, but using an installed a setuptools entry-point would not.  The reason is that _STDOUT (a TextIOWrapper on Python3) may or may not be flushed at program exit_ (http://bugs.python.org/issue17852), and it apparently wasn't when the entry-point was used.

Adding a call to `STDOUT.flush()` at the end of `main` solved the issue.

**Comment by tomduck** [comment]
That is a **great** catch.  I just posted pandoc-eqnos 0.6 to pypi.  Would you mind testing it to confirm the problem is solved?  Thanks!

**Comment by anntzer** [comment]
Works for me.  Happy new year!

**Comment by tomduck** [comment]
_Fantastic._  Thanks for solving the problem.  Happy new year to you too!

**Comment by anntzer** [comment]
I had in the meantime switched to using pandoc-crossref, which has the advantage of providing cleveref support (but requires installing the whole Haskell platform :-()  Do you plan to add the same support at some point?

**Comment by tomduck** [comment]
Interesting idea.  I'm not sure how to implement this in a way that wouldn't break when pandoc eventually gets equation number and references.  My hope in following the spec developed in [pandoc Issue #813](https://github.com/jgm/pandoc/issues/813) was to allow for a smooth transition.  Maybe we should bring up cleverref support in that discussion to get some guidance.
