### ISSUE TITLE
Provide instructions for building a release from source code

### ISSUE THREAD

**Issue by cplerch** [tomduck/pandoc-eqnos#40]

**Comment by tomduck** [comment]
Yes, I agree this is needed.  In the mean-time, the best way to install from the source root is

     $ pip install -e . --user

**Comment by tomduck** [comment]
This suggestion is now part of the new [2.0.0 branch](https://github.com/tomduck/pandoc-fignos/tree/2.0).  The instructions are in the [README.developers](https://github.com/tomduck/pandoc-fignos/blob/2.0/README.developers) file, which is referenced by the main README.md.

Thank you for your feedback.

Cheers,
Tom
