### ISSUE TITLE
Unclear error message when used with pandoc --to=jats

### ISSUE THREAD

**Issue by dhimmel** [tomduck/pandoc-eqnos#43]
In a [build](https://ci.appveyor.com/project/manubot/rootstock/builds/30189442#L311) for https://github.com/manubot/rootstock/pull/82, I'm getting the following error:

```
  File "/home/appveyor/miniconda/envs/manubot/lib/python3.7/site-packages/pandoc_eqnos.py", line 213, in _add_markup
    return ret
UnboundLocalError: local variable 'ret' referenced before assignment
```

The corresponding pandoc-eqnos function is:

https://github.com/tomduck/pandoc-eqnos/blob/6341171ea345d4b176455b4e705f31934597e92d/pandoc_eqnos.py#L178-L213

We're specifying pandoc's `--to=jats`, which does not appear to be supported by this function. Should there be a final else to capture unsupported formats and either:

1. provide a more clear error message
2. issue a warning that pandoc-eqnos does not support JATS, but proceed such that the pandoc command does not fail

**Comment by tomduck** [comment]
Thank you for the report and sorry for the long wait.  This is definitely a bug.  I have fixed it in the `nextrelease` branch.  If the problem should reappear following the next release, please feel welcome to re-open this issue.

Tom

**Comment by dhimmel** [comment]
Thanks! Reference the commit at https://github.com/tomduck/pandoc-eqnos/commit/d479d147ecc64c0007c49a0e26c000b8408ad3af

**Comment by tomduck** [comment]
Sorry, Daniel, but I am not sure if you are asking me to do something here?

**Comment by dhimmel** [comment]
Ah no. You are all good. Just wanted to link to the commit that fixed the
issue in case that is ever helpful in the future.
