### ISSUE TITLE
Counterintuitive behaviour with `pandoc-eqnos` and images with html output

### ISSUE THREAD

**Issue by kdheepak** [tomduck/pandoc-eqnos#48]
If I have the following markdown file:

```markdown
![](/images/diagram.png){ .fullwidth }
```

running `pandoc test.md -o test.html` gives this:

```
<p><img src="/images/diagram.png" class="fullwidth" /></p>
```

however,

running `pandoc --filter=pandoc-eqnos test.md -o test.html` gives this:

```
<figure>
<img src="/images/diagram.png" class="fullwidth" alt="" />
</figure>
```

I think it is counterintuitive that using `pandoc-eqnos` modifies the output for `img`s.

I initially thought this was due to the interaction between `pandoc-fignos` or `pandoc-tablenos`, but that does not seem to be the case. I've uninstalled `pandoc-fignos` and `pandoc-tablenos` from my machine and I still get the same behavior. I'm also not able to find any code in this repo that would be responsible for this, so I'm not really sure what is going on.

**Comment by kdheepak** [comment]
After doing a little bit of reading and experimenting, I think this is related to pandoc's implicit figures and not actually an issue with pandoc-eqnos. I'll close this.

**Comment by tomduck** [comment]
Thanks, @kdheepak.
