### ISSUE TITLE
eqnos-number-by-section=False is broken for (X)HTML

### ISSUE THREAD

**Issue by stroobandt** [tomduck/pandoc-eqnos#49]
The `--metadata` customisation `eqnos-number-by-section=False`

    -M eqnos-number-by-section=False

is broken for (X)HTML. Numbering restarts with each section.

[Similar issues and possible solutions](https://github.com/tomduck/pandoc-xnos/issues/15) have been reported for `fignos-number-by-section` and `tablenos-number-by-section`.

**Comment by tomduck** [comment]
Thank you for this report, and sorry for the long wait.  The problem is now fixed in the `nextrelease` branch.  Should the problem reappear after the next release, please feel welcome to re-open this issue.

Tom

**Comment by tomduck** [comment]
pandoc-eqnos 2.2.0 is now released.  --Tom
