### ISSUE TITLE
Use with pandoc 1.16 

### ISSUE THREAD

**Issue by mjedmonds** [tomduck/pandoc-eqnos#5]
I'm trying to use pandoc-eqnos when using a template and I can't figure out why it's not working. I assume the problem _might_ be related to the template. The demo works. Here's my pandoc command:

```
pandoc --filter pandoc-eqnos --number-sections --template=/Users/mark/.pandoc/default.latex -o file.pdf file
```

In the file, I have: 

```
$$ p(y|x) = \frac{p(x|y)p(y)}{p(x)} $$ {#eq:bayesrule}
```

And what's in the resulting pdf:

<img width="628" alt="screen shot 2015-12-04 at 20 31 02" src="https://cloud.githubusercontent.com/assets/6476860/11606016/f69b583c-9ac5-11e5-869e-db578cfba148.png">

Any hints/suggestions?

Running pandoc 1.16. Built from source, adds image attributes such {width=}. Might be a related issue...

See: https://github.com/jgm/pandoc/commit/244cd5644b44f43722530379138bd7bb9cbace9b

**Comment by tomduck** [comment]
Thanks for the report.  I should have a fix within a day or two.  Cheers!

**Comment by tomduck** [comment]
I have reproduced the error and am working on a fix.

**Comment by tomduck** [comment]
I pushed a fix to github.  If you wouldn't mind, please install from source and see if this works for you.  If everything is OK, then I will post a new version to pypi.

Thanks again for the report.

**Comment by mjedmonds** [comment]
Works for me; thank you for the quick fix!

<img width="799" alt="screen shot 2015-12-30 at 16 06 10" src="https://cloud.githubusercontent.com/assets/6476860/12058206/4d071a78-af0f-11e5-835c-df21cfa7276e.png">

**Comment by tomduck** [comment]
Excellent.  I have posted pandoc-eqnos v0.5 to pypi.  Cheers!
