### ISSUE TITLE
writing mistake at the install command

### ISSUE THREAD

**Issue by ilcpm** [tomduck/pandoc-eqnos#52]
![image](https://user-images.githubusercontent.com/36830343/85882040-27ce2e80-b811-11ea-800b-731e35f4cdde.png)

`pip install pandoc-eqnos --user`
not
`pip install pandoc-fignos --user`

🤣

**Comment by khalid-hussain** [comment]
I've created a pull request to fix this.

https://github.com/tomduck/pandoc-eqnos/pull/53

**Comment by tomduck** [comment]
Good catch!  I merged your PR into the `nextrelease` branch.  Thank you for this help.

Cheers,
Tom

**Comment by tomduck** [comment]
pandoc-eqnos 2.2.0 is now released.  --Tom
