### ISSUE TITLE
Feature request: is it possible to have bracketed cleveref equations?

### ISSUE THREAD

**Issue by kleinbottle** [tomduck/pandoc-eqnos#57]
I note that if the bracketed version of equations is desired, one has to forswear the benefits of cleveref. Is it possible to have the best of both worlds with a  bracket key or option available with cleveref?

Thanks for a swell filter.

**Comment by tomduck** [comment]
Hi, @kleinbottle.  Thanks for your comments on the filter.  ☺︎

I just pushed out a new release of pandoc-eqnos that does what you want (I think!).  Please upgrade using `pip install pandoc-eqnos --user --upgrade`.

It is now possible to get both clever and AMS-style (i.e., bracketed) references with the following header YAML:
```
eqnos-cleveref: True
eqnos-eqref: True
```

If this accomplishes what you want, then please go ahead and close this Issue.

Cheers,
Tom

**Comment by kleinbottle** [comment]
Thank you, @tomduck. It works as expected. I am closing the issue.

**Comment by tomduck** [comment]
Wonderful.  Enjoy.  ☺︎  --Tom
