### ISSUE TITLE
Cannot use whitespace in IDs

### ISSUE THREAD

**Issue by ZelphirKaltstahl** [tomduck/pandoc-eqnos#8]
It would be great to be able to use whitespaces. Consider for example wanting to create a list of equations in a document. Wouldn't want underscores in the list of equations there. When whitespace usage is not possible, one would have to somehow transform for example underscores to whitespace in a pandoc template.

**Comment by tomduck** [comment]
Thanks for your feedback, @ZelphirKaltstahl.  I have been mulling this over for a few days.

I did a little research and found that html5 [does not](https://www.w3.org/TR/html5/dom.html#the-id-attribute) allow spaces in #ids.  Pandoc's attributes are modeled after html attributes.  So I'm not sure that allowing spaces in #ids for pandoc-fignos is a good idea.  I want to be as "forward compatible" as possible.

Thoughts?

**Comment by ZelphirKaltstahl** [comment]
I didn't think about HTML5 ids before and only thought about PDF. Two ideas pop up:
1. Still allow whitespaces, put the responsibility on the user to use the right format for what they want to generate.
2. Keep it how it is, mabye a filter should be written to transform the underscores to whitespaces, if the user wishes to do so.

I don't know if it's possible to give any parameters to the eqnos filter. If that's possible from the command line, one could add a parameter, which decides, whether or not underscores or any other as a parameter given separator will be converted to whitespace.
I suppose the filter does not know what document format will be created by Pandoc, does it? If it did, one could depend on that.

**Comment by tomduck** [comment]
Thanks, @ZelphirKaltstahl.  I'm still not clear on what the use case is for this feature.  Could you please provide me with some example markdown that illustrates a need?

In answer to your questions:
1. It is possible to add command-line arguments; and
2. The filter _does_ know the destination format.

**Comment by ZelphirKaltstahl** [comment]
The use case would be the following:

`$$some math mode code$$ {#eq:My_Equation_Name}`

With this there is a problem. Either you remove the underscored and replace them with whitespace, which causes the filter fail to work properly, because it seems to expect a single word as an ID, or you leave it like it is, but then if you want to have a "Table of Equations" in a PDF, there will be underscored in the text of the Table of Equations, serving as links to the equations, which looks ugly.

This of course is only important, if you want to have a Table of Equations at all. I think, however in many papers or scientific books you might want one, because there are so many equations and some of them might be especially important for an area of expertise, so that you need to look them up often. Then a Table of Equations comes in really handy.

**Comment by tomduck** [comment]
Oh, OK.  I see.  How are you generating the table of equations?

**Comment by tomduck** [comment]
The reason why I ask this is that there may be a better way to provide text for a Table of Equations than by using the equation identifier.  See, for example, the discussion in [Issue #9](https://github.com/tomduck/pandoc-eqnos/issues/9).  We're working on introducing an equation tag that supports arbitrary text (including spaces).  Once I understand how your Table of Equations is generated, we can come up with a solution.

**Comment by ZelphirKaltstahl** [comment]
I took that part of the code out of my template, but let's see if I can find it again... I followed some stackexchange posts for that.

I think I tried the solution of this post: http://tex.stackexchange.com/a/14328
But right now I can't even get it to compile anymore without errors, so I am not sure.

**Comment by tomduck** [comment]
Wow, that's some fancy LaTeX wizardry.  The `\label` marker is being used as literal text.  The difficulty for pandoc-eqnos is that the `\label` marker comes from an id attribute.  Spaces are not allowed in id attributes by either the html spec or pandoc.  As such, I really can't support them here.

The main problem I see is that LaTeX doesn't have good support for Lists of Equations (unlike for either figures or tables).  The reason for this, I imagine, is that equations normally don't have captions.

Perhaps some markdown like this would suffice:

```
List of Equations
-----------------

 1. Eq. {@eq:id1}: Write caption here.

 2. Eq. {@eq:id2}: Write caption here.
```

Although the list isn't automatically generated, there is the advantage that this will work with all of pandoc's output formats -- a key goal of pandoc-eqnos.

**Comment by tomduck** [comment]
I assume that this should be considered resolved.  Please re-open if otherwise.  Cheers.
