### ISSUE TITLE
Allow arbitrary text as actual label

### ISSUE THREAD

**Issue by davidanthoff** [tomduck/pandoc-eqnos#9]
It would be nice if one could label equations with any arbitrary text, in addition to the automatically generated numbers. I'm not sure what syntax would be good, but say something like this:

```
$$x=y+z$$ {#eq:identifier:B.2}
```

would lead to output that looks like this

```
x = y + z       (B.2)
```

Would also be great if it also worked without an identifier, something like this:

```
$$x=y+z$$ {#eq::B.2}
```

There are lots of syntax options that would achieve this, and I'm not sure what would be most consistent with the pandoc plans, I guess ideally this might be syntax that eventually pandoc would also pick up...

**Comment by tomduck** [comment]
Thanks, @davidanthoff.  This is an interesting idea.

Can you explain to me what use case you envision for this feature?

For example, a label of "B.2" suggests to me that it is the second equation of Appendix B.  In this case, one could use the prefix "B." and let the number be automatically generated.  But perhaps you are thinking about something else entirely.

The trick will be finding the appropriate feature in LaTeX (e.g., [`\numberwithin`](https://en.wikibooks.org/wiki/LaTeX/Labels_and_Cross-referencing#numberwithin)), and then emulating it for other formats.

**Comment by davidanthoff** [comment]
We have a document where we use all sorts of different labels for equations. For example, sometimes we label one equation (CO2.1), and then later label another version of that equation as (CO2.1'). We also use different first parts within the label per chapter, so in one chapter we might have one equation labeled (CO2.1) and another one (CH4.1) and so on. I think our use case is so non-uniform that no automatic numbering scheme could cover it.

I think a free-form labeling feature would also be great as a "last" resort for anything, at the end of the day there will always be some corner cases that an automatic system misses, and if there is a free form option, everyone should be able to achieve any label.

In terms of output: For LaTeX I think one can just use the \tag{blabla} option within an \begin{equation} block? But I'm not LaTeX expert. MathJax also seems to pick such \tag{blabla} labels up, so for HTML output that would at least work for MathJax. The new equation labeling feature in Word 2016 is free form in any case. I think for rst you output freeform text already, so that would also work? But I'm new to pandoc and most of these formats, so not sure...

**Comment by tomduck** [comment]
Your point makes sense.  I wonder if a syntax like this would be better:

```
$$ x=y+z $$ {#eq:identifier tag="B.2"}
```

This would allow completely arbitrary text to be used in the tag.

Thoughts?

**Comment by davidanthoff** [comment]
Yes, that is better! I'm not sure what the most "markdown-like" syntax would be, I haven't followed that format long enough to have a feel, so I just trust you on that :) Only two other considerations, I almost feel that both could be ignored for now:

1) What about math in the tag? I don't need it and probably best to ignore, but at some point someone will probably bring it up ;)

2) My understanding is that there might be a chance that the original syntax in this package here might be adopted by pandoc itself at some point? Is that so? If yes, it might make sense to bring the pandoc crowd into the discussion here, thus maybe increasing the chance that they will adopt the syntax for tags at some point for core pandoc?

**Comment by tomduck** [comment]
I have pushed some new code to GitHub that implements this feature.  You can install it using

```
pip install git+https://github.com/tomduck/pandoc-eqnos.git
```

The syntax is currently

```
$$ x=y+z $$ {#eq:id tag="B.2"}
```

as we discussed earlier.  Please let me know if you have any problems with it.

I haven't made a release yet, but will as soon as I am confident everything is working.  I need to do more testing and update the docs.

In answer to your questions:
1. Math in tags works so long as it is not mixed with regular text.  This feature was necessary to permit the primed notation you were interested in.  Math in tags should be surrounded with single dollar-signs like `$\mathrm{CO2.1'}$`.  The `\mathrm` is used to get an upright (non-italic) font.
2. I agree that we should feed what we learn back into the pandoc process.  If the debate there leads to a different decision then we can make the necessary adjustments.

Thanks again for a great suggestion.  I'm really pleased with how it is working out.

**Comment by davidanthoff** [comment]
And this also all works, so I'm closing this issue, thanks!

**Comment by tomduck** [comment]
w00t w00t!  :o)
